Set Owner Dashboard to render property data by owner logged in and Fix Vendor & Property Forms
labs13-property-mgr/frontend pull request #46
Opened 2019-06-22 03:07 UTC by tca88

# Description

**Set Property Owner Dashboard to render property data by owner logged in. Edited vendor and property forms to add properties and vendors containing specific owner ids and populate addressbook, cards and the property dashboard appropriately. Added a prompt message for property owner new account holders to get started by adding their first property.**

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ x] Ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

2019-06-22 15:14 UTC, cori-peck requested changes
Pulled locally, add a property works, love the new welcome message. Logged out and logged back in and the property I added remains in the dashboard. Looks Awesome!

Change/Fix Request - Adding a vendor is listed as a feature on this PR but it is not working?

2019-06-22 17:11 UTC, cori-peck commented
@ryanboris does the postgres db on Heroku automatically clear out every 24 hours like it does with sqlite?

2019-06-22 17:17 UTC, cori-peck approved these changes
Nevermind - everything works. backend db was wiped so test user data wasn't working. Good to merge

2019-06-23 04:58 UTC, secantsquared approved these changes

2019-06-23 04:58 UTC, merged